### ISSUE TITLE
Naked call to console.log

### ISSUE THREAD

**Issue by TrevorBurnham** [leppert/remotipart#1]
On line 22 of jquery.remotipart.js, there's a call to `console.log`. Calling `console.log` can cause serious errors in some browsers when it doesn't exist (try it in Firefox, for instance). I'd strongly recommend either removing the line altogether or wrapping it in `if (console && console.log)`.

**Comment by leppert** [comment]
Good catch - that was a forgotten debugging call. It's been removed and a patched version has been released as v0.1.1.
