### ISSUE TITLE
How can I install the latest version of the gem?

### ISSUE THREAD

**Issue by pomartel** [leppert/remotipart#14]
It seems the gem is not up to date on rubygems.org :

http://rubygems.org/gems/remotipart

Is there something I don't understand?

**Comment by JangoSteve** [comment]
Sorry, we simply hadn't released the latest version yet on rubygems.org. I went ahead and released version 0.3.1 just now. Try again.

**Comment by pomartel** [comment]
It works, thank you!

**Comment by JangoSteve** [comment]
Awesome, glad to hear it.
