### ISSUE TITLE
Does Remotipart need all 24kb jQuery Form Plugin?

### ISSUE THREAD

**Issue by julianalucena** [leppert/remotipart#19]
I started to use the remotipart gem, but I'm a bit worried about the size of jQuery Form plugin (24kb). Does It really need all the jQuery Form plugin or just a part of it?

**Comment by JangoSteve** [comment]
The form plugin shrinks to under 10kb when minimized I believe. But no, remotipart doesn't need all of it. It needs the `.ajaxSubmit()` function, which is [lines 46-467](https://github.com/malsup/form/blob/master/jquery.form.js#L46-467).

**Comment by julianalucena** [comment]
I'll see what is the best option to the application. Thank you.

**Comment by JangoSteve** [comment]
No prob. Let me know what you figure out, and if there's any way to improve remotipart ;-)
