### ISSUE TITLE
Question: how can I hook into before submit, complete, etc?

### ISSUE THREAD

**Issue by ramontayag** [leppert/remotipart#2]
Not really an issue, but more of a question. Didn't know where else to ask. How can I hook into the callbacks? I want to be able to do stuff before the form submits. Thanks!

**Comment by leppert** [comment]
The callbacks are fired as standard jQuery events and you should be able to bind to them just like the standard jQuery Rails plugin. For example:
    $('form').bind('ajax:before', function(){
        alert('test');
    });
Look in remotipart.js to see the callbacks available. Further documentation on jQuery events can be found here:
http://api.jquery.com/category/events/

If you need additional help, feel free to send me a direct message here on Github.

**Comment by ramontayag** [comment]
Thanks a lot! You saved me loads of time. I found your gem when I ran into this problem: http://stackoverflow.com/questions/4099516/rails3-how-to-get-a-js-erb-to-insert-html-into-your-page

**Comment by leppert** [comment]
Glad you found it helpful and thanks for the Stackoverflow link. It's always nice to see something you've created save other people the time that was spent trying to solve a specific problem the first time around.
