### ISSUE TITLE
$.rails is undefined

### ISSUE THREAD

**Issue by malagant** [leppert/remotipart#20]
Hi,

I can't get it to work. I have:

```
- public/javascripts/jquery/jquery-1.4.4.min.js
- public/javascripts/rails.js
- public/javascripts/jquery.form.js
- public/javascripts/jquery.remotipart.js
```

in this order in my layout and all I can see on the console is:

cannot call handleRemote on undefined.

So $.rails ist definitely not defined.

I have the correct version of rails.js for remotipart 0.3.4.

Any hints?

Cheers
Michael

**Comment by JangoSteve** [comment]
Hmm, there is definitely something funky going on there. Are the javascripts being included in the head of the layout in the right order?

**Comment by malagant** [comment]
I got it working. Most important, the jquery-version I use now is 1.6.1. 1.4.4 didn't work. Thanks for the efforts.

**Comment by JangoSteve** [comment]
That's really weird, I have no idea why that'd be the case.

**Comment by jobinthepast** [comment]
I'm using:
- jquery 1.6.1 (using CDN file).
- rails.js is present and included layout.
- jquery.form.js and jquery.remotipart.js is in public/javascripts/ and included in layout.

and here's the list of my JS files:

| | |-application.js
| | |-facebox.js
| | |-jquery.autogrow.js
| | |-jquery.dump.js
| | |-jquery.form.js
| | |-jquery.jeditable.autogrow.js
| | |-jquery.jeditable.js
| | |-jquery.nivo.slider.js
| | |-jquery.nivo.slider.pack.js
| | |-jquery.remotipart.js
| | |-jquery.timeago.js
| | |-jquery.uploadify.v2.1.4.min.js
| | |-jquery.watermark.min.js
| | |-rails.js
| | |-swfobject.js
| | |-underscore-min.js

remotipart version 0.4.1

have exactly the same error: $.rails is undefined , $.rails.handleRemote(form) on line #78

any idea?

Thanks,
-Giang

**Comment by malagant** [comment]
Actually, I resolved my issue with checking if the correct versions where
uses.
Try to find $.rails in rails.js. If it's not there, you got the wrong
version.

Let me know if that helped, otherwise I will dig deeper into it.

Cheers
Michael

Am 14.08.11 22:35 schrieb "ndgiang84" unter
reply@reply.github.com
:

**Comment by jobinthepast** [comment]
Hi Michael,

There's no "$.rails" in my rails.js. Where can I find the right version of rails.js?

I often do "rails g jquery:install" and recently I have jquery files and jquery_ujs.js created (which some months ago I got rails.js created)

I'm working on a legacy codebase so I don't want to break things with my changes. Could you tell me a safe way to get remotipart work?

Thanks,
-Giang

**Comment by jobinthepast** [comment]
Hi Michael,

I got it work. Replace the rails.js by the jquery_ujs.js created by "rails g jquery:install"

Thank you very much Michael.

-Giang

**Comment by malagant** [comment]
Hi Giang,

I guess you should use an updated version like this one here
(https://github.com/rails/jquery-ujs/blob/master/src/rails.js).

I'm sure this will make life easier for you ;)

Cheers
Michael

Am 14.08.11 22:47 schrieb "ndgiang84" unter
reply@reply.github.com
:

**Comment by JangoSteve** [comment]
@ndgiang84, glad you got it all figured out. @malagant, thanks for your help! :-)

For future reference, the latest jquery-rails gem (>=1.0.12) properly gets rid of the old jquery-ujs and installs the new one when you run `rails g jquery:install` for rails 3.0 apps. But for rails 3.1 apps, it bundles the js files inside the gem, so you must manually delete any existing rails.js or jquery_ujs.js files in your public/javascripts folder.

**Comment by akostadinov** [comment]
For me it was an issue with order of `require` in `app/assets/javascripts/application.js`.
