### ISSUE TITLE
Form Post Format when submit button is disabled

### ISSUE THREAD

**Issue by l4u** [leppert/remotipart#21]
My script works with firefox, which the form is posted to js.
In rails log, I got Processing by ReviewsController#create as JS

But when I use chrome or IE8, I got  Processing by ReviewsController#create as HTML. it is requesting an HTML, but not a JS.

This happens when I disabled the button when it is clicked.

**Comment by JangoSteve** [comment]
Can you inspect what exactly is the `ACCEPT` header that is getting sent to the server?

It should probably either be `text/javascript` or `*/*;q=0.5, text/javascript`.

**Comment by JangoSteve** [comment]
I'm going to close this out. If you're still having problems, can you open the issue at the currently-maintained repo over at https://github.com/JangoSteve/remotipart/issues?
