### ISSUE TITLE
Multiple uploaded files on same form

### ISSUE THREAD

**Issue by jerodsanto** [leppert/remotipart#22]
Hey, thanks for the great library!

I got it working just fine when uploading  a single file via an ajax form, but it fails when multiple files are uploaded on the same form.

What happens is the form will "double submit". Once via ajax, and then immediately after it will also submit a regular POST which then redirects the page. Very strange.

I dug through your JS and I can't really see where this might be a problem, but admittedly a lot of the fancy footwork is happening in form.js.

Any ideas why this might be? I can provide code samples or debug output if it'd be helpful.

Thanks!

-Jerod

**Comment by JangoSteve** [comment]
Hmm, I'll have to look into this. To clarify, is it 2 file fields with the same name, like in an array? E.g. multiple `myfile[]` fields, or is it different fields with different names?

**Comment by jerodsanto** [comment]
It is actually part of a dynamic `fields_for` implementation where a Note (which is being created via AJAX) `accepts_nested_attributes_for` its Documents. The Documents have the file fields on them and are added when a user desires. The nested document markup is something like this:

```
<input data-validate="true" id="note_documents_attributes_1310673350586_data" name="note[documents_attributes][1310673350586][data]" type="file">

<input data-validate="true" id="note_documents_attributes_1310673352283_data" name="note[documents_attributes][1310673352283][data]" type="file">
```

This works just fine when a single Document is added to the form, but once there are two of them it fails as described.

**Comment by JangoSteve** [comment]
I'm having trouble reproducing this. I just [added a second attachment and file field](https://github.com/JangoSteve/Rails-jQuery-Demo/commit/8725888e438f0480a59c7746ef22dd0085e239c6) in the demo app and everything seems to work fine. Could you take a look maybe and see what changes are necessary to make the demo app exhibit the same behavior?

[See demo app here](https://github.com/JangoSteve/Rails-jQuery-Demo/tree/remotipart).

**Comment by jerodsanto** [comment]
Hey, glad to see it working there. I think my problem is a conflict between your js and [client_side_validations](https://github.com/bcardarella/client_side_validations) js. We've had some file field problems with his gem before, but for some reason that didn't click with me until I saw yours working (sans js validations).

For now I've just disabled his validations on the file fields and everything works great.

Closing this issue. Cheers!

**Comment by JangoSteve** [comment]
Oh interesting. I remember having to resolve some issues between the validations.js and rails jquery-ujs in the past. If you figure out what the conflict is, let me know if there's anything we need to do on this end. Thanks!

**Comment by ankitjain200292** [comment]
If I have multiple files on the same form and on validation fails it is removing the file fields from the form. EX: If i have 3 files on the form and validation field it will remove the 1 file field and 2 file fields will be present and if again validation fails then the 1 file field will be visible. 

Please let me know in case anybody else facing the issue and any help is much appreciated.

Banner image field gone after validation fails.
![screenshot from 2017-10-31 17 38 58](https://user-images.githubusercontent.com/5794971/32223206-6f5d4818-be62-11e7-9f5c-d8382c4ed5d3.png)

**Comment by leppert** [comment]
@ankitjain200292 This repo has moved. Check the README.
