### ISSUE TITLE
Other forms of response

### ISSUE THREAD

**Issue by mahemoff** [leppert/remotipart#24]
Is there any way to avoid wrapping the response in a textarea? I'd like to just return an empty 200 response.
Also, is there any way to request an HTML response?

(The rest of my app doesn't use RJS, so I'm hoping to maintain that convention throughout. Sorry if this is already covered in the docs, but I can't see it anywhere.)

**Comment by JangoSteve** [comment]
This is no longer the active repo for this project. See https://github.com/JangoSteve/remotipart.

Try upgrading to the latest version of remotipart and view the updated docs at https://github.com/JangoSteve/remotipart/blob/master/README.rdoc and http://www.alfajango.com/blog/remotipart-rails-gem/
