### ISSUE TITLE
Don't truncate response if it includes </textarea>

### ISSUE THREAD

**Issue by BMorearty** [leppert/remotipart#25]
If the AJAX response is HTML that contains the string `</textarea>`, remotipart seems to truncate the entire response from that point on. Presumably this is related to the fact that the entire response is wrapped in a `<textarea>` tag.

This makes it impossible to return HTML with a textarea tag.

I could look at it but if someone else knows exactly where the problem is, go for it.

**Comment by JangoSteve** [comment]
This repo is no longer maintained. There currently an open ticket on the maintained repo, I'll take a look at pulling it in now. https://github.com/JangoSteve/remotipart/pull/7

**Comment by BMorearty** [comment]
Thanks, @JangoSteve. That would be a big help. Sorry about the cross-post.
