### ISSUE TITLE
Not working on Chrome v17.0.963.46

### ISSUE THREAD

**Issue by BenZhang** [leppert/remotipart#26]
It works fine on IE9 or FireFox, but when I tried to upload file via chrome. It just does nothing. The server doesn't receive any data, and no error pop up.

**Comment by JangoSteve** [comment]
It sounds like there may be something else wrong with the setup. I have a demo app I use for integration specs for rails jquery-ujs, and there is a separate branch I use for the test suite for remotipart. I have Chrome v17.0.963.46 as my daily browser and it's working fine.

My initial recommendation, considering that it's behaving fine in some browsers but not others, would be to pay really close attention to the Content-Type header in the request and response. If this is off, I've seen some browsers guess right and others wrong. But it could also be something else entirely.

Check out the [demo app here](https://github.com/JangoSteve/Rails-jQuery-Demo/tree/remotipart).

**Comment by JangoSteve** [comment]
Also, take a look at the homepage of this repo. This repo is no longer maintained. May want to check out the active repo for remotipart: [JangoSteve/remotipart](https://github.com/JangoSteve/remotipart)

**Comment by BenZhang** [comment]
Thank you very much

**Comment by JangoSteve** [comment]
Were you able to figure it out?

**Comment by BenZhang** [comment]
Yes. it turns out it was not working on my VM uploading the file through apache, but it is working fine while not using VM. However, I am happy with the result, after all there is only few people will use VM.
