### ISSUE TITLE
Script5: Access denied when trying to submit form in IE9 + gmail

### ISSUE THREAD

**Issue by DzmitryNikitsin** [leppert/remotipart#30]
when i submit form with file attached it works fine if i go directly to site. 

but it doesn't work and throw Access Denied in IE9 when i came to site from gmail account(from link in gmail account) and trying to submit form with file attached. 

I did investigation here - it's issue in jquery.iframe-transport, it throw exception when i am submitting the form. Spent 3 days but didn't found how to fix that. It would be appreciated if you'll be able to fix this issue.

**Comment by JangoSteve** [comment]
I believe this is already an issue at https://github.com/JangoSteve/remotipart/pull/49. If you have additional info, please post it on that ticket in the currently maintained repo.

**Comment by DzmitryNikitsin** [comment]
it's still not resolve an issue. 
Can you reopen this issue

**Comment by JangoSteve** [comment]
No, this repo is no longer maintained. Please see https://github.com/JangoSteve/remotipart/pull/49.
