### ISSUE TITLE
Double post

### ISSUE THREAD

**Issue by brandonchua** [leppert/remotipart#31]
Remotipart is doing double post. I read from another closed issue not to include jquery.form but in instructions you mention we should. So what should I actually do then?
I am on rails 3.2.3 by the way. Thanks

This is my application.js :

//= require jquery
//= require jquery_ujs
//= require jquery.form
//= require jquery.remotipart
//= require jquery.colorbox
//= require usernav
//= require chosen-jquery

**Comment by JangoSteve** [comment]
If this is still an issue, please post it at the currently maintained repo, JangoSteve/remotipart.
