### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by nullset** [leppert/remotipart#34]
I think the docs for installation procedures may be out of date. The docs tell Rails 3.1 (asset pipeline) users to include this:

``` javascript
//= require jquery.form
//= require jquery.remotipart
```

however doing so seems to throw a JS error.

> Uncaught Error: Sprockets::FileNotFound: couldn't find file 'jquery.form'

If, instead I do this:

``` javascript
//= require jquery.iframe-transport
//= require jquery.remotipart
```

things seem to work as expected.

**Comment by JangoSteve** [comment]
Hey, this isn't the currently maintained repo (which is why it's out of date). Please see [the current repo](https://github.com/jangosteve/remotipart).

**Comment by nullset** [comment]
Thanks, didn't even notice that ;-)
