### ISSUE TITLE
IE Problems

### ISSUE THREAD

**Issue by springbok** [leppert/remotipart#6]
Hi,

Firstly thanks for the work on this gem. I have my form working without any issues on Chrome and FF but I'm having some problems with IE. When I try and upload the file I'm getting a "File download - security warning" dialog displayed. 

Tracing into the server code it looks like when using IE I'm not getting the ActionDispatch::Http::UploadedFile object for the file_field_tag field, instead I'm only getting the name of the file for this field in the params.

Any ideas on why this is happening with IE?

Thanks,

Etienne.

**Comment by leppert** [comment]
My guess is that this is an issue with the [jquery form plugin](http://jquery.malsup.com/form/) which actually negotiates the transfer of the data but you never know. What versions of IE have you tested it in?

**Comment by springbok** [comment]
Thanks for the response, I've tested it with IE7 & IE8

**Comment by springbok** [comment]
Sorry hit the wrong button, did not mean to close the issue.

**Comment by springbok** [comment]
Ok after spending a few hours on this it turns out I was still using jquery 1.4.2 not 1.4.4, after upgrading everything worked as expected.

Thanks,

Etienne.

**Comment by JangoSteve** [comment]
Any ideas here? I'm still having this problem with IE7 and IE8. Using the latest jquery.form.js plugin and jquery 1.4.4 (also tried 1.5), and the latest compatible rails.js. It appears that IE sees the ".js" extension that this plugin adds on to the request and assumes it wants to download a file.

**Comment by JangoSteve** [comment]
Ah, nevermind, finally realized I wasn't using the `<%= remotipart_response do %>` block.
