### ISSUE TITLE
Getting undefined method `remotipart_response'

### ISSUE THREAD

**Issue by burlesona** [leppert/remotipart#8]
I'm running into one problem I don't get... I have remotipart installed properly, it's in my gemfile and I ran bundle install, I also generated the js and have all the dependencies. When I use this in a form everything works fine until the app hits my "create.js.erb" file, at which point I get:

ActionView::Template::Error (undefined method `remotipart_response' for #<#Class:0x00000101a7e728:0x00000101a7bbe0>):

Any suggestions?

Thanks for the amazing gem, this is a life saver for me!

**Comment by burlesona** [comment]
Um, sorry. I just needed to reset my server.

Seriously you deserve a medal for making this so simple, I've been working for the past week to get ajax uploading working and your gem took less than 30 minutes to integrate into my app -- even with my obvious goof :)

**Comment by leppert** [comment]
Glad it worked out!
